export const BANNED_WORDS = [
  "ASS", "ARSE", "DAMN", "DICK", "FUCK", "SHIT", "PISS", "BITCH", "CUNT",
  "TWAT", "COCK", "WANK", "PRICK", "SLUT", "TIT", "CRAP", "BUGGER", "BOLLOCKS",
  "BINT", "NIGGER", "NEGRO", "KIKE", "CHINK", "SPIC", "TRANNY", "RETARD",
  "FAGGOT", "FAG", "DYKE", "GOOK", "NAZI", "HONKEY", "CRACKER", "JUNGLEBUNNY",
  "TAR BABY", "WETBACK", "HEEB", "GYPPY", "GYPO", "MUZZIE", "MUZZY", "ZIONIST",
  "ISLAMOPHOBE", "WHORE", "HO", "SKANK", "TRAMP", "HAG", "BROAD", "SEX",
  "SEXY", "HORNY", "ORGY", "ANAL", "BDSM", "PENIS", "VAGINA", "CLIT", "DILDO",
  "BJ", "BOOB", "BOOBS", "CUM", "JIZZ", "RIMJOB", "HANDJOB", "BANG", "BLOWJOB",
  "SCREW", "HUMP", "FELLATIO", "CUNNILINGUS", "GENITAL", "NUDE", "XXX"
];
